import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header"; // Ensure this path is correct

const JetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-JetBrainsMono",
});

export const metadata = {
  title: "Nolan's Portfolio",
  description: "Generated by Dev Nolan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={JetBrainsMono.variable}>
        <Header />
        {children}
      </body>
    </html>
  );
}
